* Blockchain node

** Concepts and purpose

*** Peer discover and transaction relay

- Blockchain node :: The blockchain node is the core component of the blockchain
  peer-to-peer network. The blockchain peer-to-peer network consists of a set of
  autonomous and self-contained interconnected nodes. The set of interconnected
  nodes forms a distributed system where each node operates independently of
  other nodes and is interconnected with other nodes through peer-to-peer
  connections
- Peer discovery :: The peer-to-peer connections are established automatically
  through the peer discovery mechanism. The peer discover mechanism starts with
  a seed node address that usually is the bootstrap node and periodically
  fetches the list of known peers from every known peer of a node. This design
  ensures automatic discovery of new nodes that have been recently added to the
  blockchain and automatic disposition of connections with nodes that have gone
  offline.
- Transaction relay :: After establishing peer-to-peer connections with other
  nodes the node starts accepting new signed transactions from clients. All
  validated accepted transactions from clients are automatically relayed to the
  list of known peers in order to propagate new validated transactions through
  the peer-to-peer network. Every node in the peer-to-peer network accumulates
  relayed validated transaction in the local pending state. The local pending
  state contains the new validated transactions to be included into the new
  proposed block

*** Block proposal, block relay, block confirmation

- Block proposer :: The block proposer is part of the consensus algorithm
  employed by the blockchain. This blockchain uses the Proof of Authority (PoA)
  consensus algorithm. Specifically, in this blockchain only the authority node
  holds the authority account that signs new proposed blocks. The authority node
  periodically with a random delay creates a new blocks from the validated
  transactions of the pending state, signs the block with the authority account
  and relays the signed proposed block to other validators to validate and
  confirm the proposed block. Other validators are all the nodes on this
  blockchain including the authority node itself. The propagation of the new
  proposed blocks happens through the block relay
- Block relay :: After a new block is created and signed by the authority node,
  the proposed block is propagated through the peer-to-peer network using the
  block relay mechanism. The block relay mechanism reuses the infrastructure of
  the transaction relay with a notable difference that the block relay mechanism
  uses the self-relay function, while the transaction relay mechanism does not.
  The self-relay function relays the proposed block to the authority node itself
  along with the list of known peers. This design separates the block proposal
  function from the block validation and confirmation function. There is only
  one block proposed in this blockchain. This design prevents forks on the
  blockchain as all nodes either confirm a valided proposed block or reject an
  invalid proposed block
- Block confirmation :: Every proposed block received through the block relay
  mechanism is validated against the coned state, and, if successful, is applied
  to the confirmed state of the node, and is appended to the local block store.
  The block validation verifies that the proposed block number and parent hash
  are in accordance with the latest confirmed state maintained on every node.
  The block validation validates also all transactions from the proposed block
  against the cloned state. If the proposed blocks is validated, the block
  becomes confirmed and is applied to the confirmed state, as well as is
  appended to the local block store. The block confirmation concludes the PoA
  consensus algorithm initiated by the block proposer. This design ensures that
  all nodes on the peer-to-peer network confirm validated blocks proposed and
  signed by the authority node in exactly the same order with exactly the same
  block content

*** Confirmed and pending state

- State sync :: When a new node joins the peer to peer network, or an
  out-of-sync node becomes online again, the state sync process fetches the
  genesis from the bootstrap node and fetches all newer confirmed blocks from
  the list of known peers in order to synchronize the node with latest confirmed
  state on the blockchain. The state sync process is also used when initializing
  a completely new blockchain on the bootstrap node. In this case a new genesis
  is persisted with the initial blockchain configuration include the initial
  owner and the initial blockchain balance. The latest blockchain state
  including both the last confirmed block and the list of pending transactions
  are maintained in the state data structure on every node
- Confirmed and pending state :: The confirmed and pending state is an in-memory
  data structure that is maintained on every node in the peer-to-peer network.
  The confirmed state reflects the account balances after applying transactions
  from from confirmed by consensus block in order. The confirmed state is
  regularly updated with state changes from the next confirmed block on the
  blockchain. The pending state accumulate new validated transactions sent
  directly to the node by clients or relayed from other nodes. The list of
  pending transactions is used to create, sign, and propose the next block by
  the authority node. The list of pending transactions is updated after the new
  proposed block is confirmed and applied to the confirmed state and added to
  the local block store. Specifically, all confirmed transactions are removed
  from the list of pending transactions

*** Streaming domain events to clients

- Event stream :: The node event stream mechanism exposes important domain
  events that occur on the blockchain node to be consumed by subscribed clients.
  The domain events that occur on the node are always available for any client
  to consume. The client subscribes to the node event stream by specifying the
  types of event the client is interested in. On successful subscription events
  of all requested event types are streamed to the subscribed client through the
  gRPC server streaming. At any moment the client can close the streaming
  without impacting event streaming to other clients subscribed to the same
  node. The node event stream mechanism provides efficient, real-time
  notification of external to the blockchain applications about the important
  domain events that occur on the blockchain e.g. confirmed blocks, confirmed
  transactions

*** The node graceful shutdown mechanism

- Node graceful shutdown :: The node graceful shutdown mechanism provides a
  reliable mechanism to notify graceful shutdown to all concurrent processes on
  the blockchain node and wait for the graceful termination of concurrent node
  processes before shutting down the node process. The node graceful shutdown
  happens after the node process receives the =SIGINT=, the =SIGTERM=, or the
  =SIGKILL= signal from the other process on the OS. The node graceful shutdown
  mechanism contributes to clean shutdown of the blockchain node. The clean
  shutdown of the node implies that after receiving the shutdown signal the node
  stops accepting new connections on the gRPC interface, the node stops
  accepting new requests on existing active gRPC connections, the node finishes
  processing all requests that have been in progress when the shutdown signal
  was received, the node correctly updates the confirmed and pending state, the
  node finishes all pending operations on the local block store and closes the
  local block store, the node stops communication with all connected peers and
  closes all open connections with active peers. The node graceful shutdown
  mechanism consists of the node shared context hierarchy that spreads all
  concurrent node processes that have to be notified about the graceful
  shutdown. When the node graceful shutdown signal is received, the node shared
  context hierarchy is canceled. This notifies all concurrent node components
  that the node graceful shutdown has started. The node graceful shutdown
  mechanism consists of the shared wait group that spreads all concurrent node
  processes that have to be notified about the graceful shutdown. When every
  concurrent node process finishes the graceful shutdown, the process notifies
  the node's main goroutine about the successful shutdown. The node's main
  goroutine waits for all node concurrent processes to shutdown gracefully

** Design and implementation

*** Node type

- Node type :: The =Node= type host all the concurrent node processes required
  to discover peers; accept, validate, and relay transactions; propose,
  validate, and relay blocks; apply validated blocks to the confirmed state,
  append validated blocks to the local block store; stream domain events to
  subscribed clients; and handle the node graceful shutdown including all
  concurrent processes. The node type contains the node configuration including
  the node and seed addresses, the node bootstrap flag, the directories for the
  local key store and the local block store, the blockchain name, the authority
  account password, the initial owner account password, the initial owner
  account balance, the period of concurrent node processes. The node type
  contains the node shared context hierarchy and the node shared wait group to
  support the node graceful shutdown mechanism. The node type hosts the event
  stream to deliver domain events to subscribed clients. The node type contains
  the confirmed and pending state and the state sync to initialize new nodes or
  synchronize out-of-sync nodes with the latest state updates on the blockchain.
  The node type hosts the gRPC server for all interactions between the node and
  other nodes, as well as interactions between the node and clients. The node
  type contains the peer discovery to automatically connect the node with other
  nodes on the peer-to-peer network. The node type contains the transaction
  relay to propagate validated transaction to the list of known peers. The node
  type contains the block proposer to periodically create, sign, and propose new
  blocks with pending transactions. The node type contains the block relay to
  propagate proposed and validated blocks to the list of know peers including
  the authority node that proposed the new block. The node type acts as an
  extensible container for concurrent node processes that support correct
  operations of the node in particular and the blockchain in general. The node
  graceful shutdown process ensures that all concurrent node processes terminate
  gracefully without throwing in-progress transactions and without corrupting
  the blockchain state and the local block store. The node type
  | ~cfg NodeCfg~                             | Node configuration                 |
  | ~ctx context.Context~                     | Node shared context hierarchy      |
  | ~ctxCancel func()~                        | Graceful shutdown context cancel   |
  | ~wg *sync.WaitGroup~                      | Node shared wait group             |
  | ~chErr chan error~                        | Concurrent processes error channel |
  | ~evStream *EventStream~                   | Node event stream                  |
  | ~state *chain.State~                      | Pending and confirmed state        |
  | ~stateSync *StateSync~                    | State sync                         |
  | ~grpcSrv *grpc.Server~                    | gRPC server                        |
  | ~peerDisc *PeerDiscovery~                 | Peer discovery                     |
  | ~txRelay *MsgRelay[SigTx, gRPCRealy]~     | Transaction relay                  |
  | ~blockProp *BlockProposer~                | Block proposer                     |
  | ~blkRelay *MsgRelay[SigBlock, gRPCRealy]~ | Block relay                        |
  #+BEGIN_SRC go
type Node struct {
  cfg NodeCfg
  // Graceful shutdown
  ctx context.Context
  ctxCancel func()
  wg *sync.WaitGroup
  chErr chan error
  // Node components
  evStream *EventStream
  state *chain.State
  stateSync *StateSync
  grpcSrv *grpc.Server
  peerDisc *PeerDiscovery
  txRelay *MsgRelay[chain.SigTx, GRPCMsgRelay[chain.SigTx]]
  blockProp *BlockProposer
  blkRelay *MsgRelay[chain.SigBlock, GRPCMsgRelay[chain.SigBlock]]
}

func NewNode(cfg NodeCfg) *Node {
  ctx, cancel := signal.NotifyContext(
    context.Background(), syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL,
  )
  wg := new(sync.WaitGroup)
  evStream := NewEventStream(ctx, wg, 100)
  peerDiscCfg := PeerDiscoveryCfg{
    NodeAddr: cfg.NodeAddr, Bootstrap: cfg.Bootstrap, SeedAddr: cfg.SeedAddr,
  }
  peerDisc := NewPeerDiscovery(ctx, wg, peerDiscCfg)
  stateSync := NewStateSync(ctx, cfg, peerDisc)
  txRelay := NewMsgRelay(ctx, wg, 100, GRPCTxRelay, false, peerDisc)
  blkRelay := NewMsgRelay(ctx, wg, 10, GRPCBlockRelay, true, peerDisc)
  blockProp := NewBlockProposer(ctx, wg, blkRelay)
  return &Node{
    cfg: cfg, ctx: ctx, ctxCancel: cancel, wg: wg, chErr: make(chan error, 1),
    evStream: evStream, stateSync: stateSync, peerDisc: peerDisc,
    txRelay: txRelay, blockProp: blockProp, blkRelay: blkRelay,
  }
}
  #+END_SRC

*** Starting the blockchain node

- Node start :: The node start process initiates all the concurrent node
  processes, sets up the node graceful shutdown mechanism, and waits for either
  the signal to gracefully shutdown the node or an unrecoverable error from any
  of the concurrent node processes. The node start process
  - Defer the node shared context cancellation when the node process is stopped
  - Start streaming domain events to subscribed clients
  - Initialize the state and create the genesis of a new node or synchronize the
    state and update the local block store of an out-of-sync node
  - Start the gRPC server with the account, transaction, block, and node
    services
  - Start the peer discovery
  - Start the transaction relay
  - Start the block proposer if the node is the bootstrap and the authority node
  - Start the block relay
  - Wait for either the node cancellation signal on the node shared context
    cancel channel or an unrecoverable error from any of the node concurrent
    processes
  - Gracefully shutdown the gRPC server
  - Wait for all node concurrent processes to gracefully shutdown before
    termination the main node process
  #+BEGIN_SRC go
func (n *Node) Start() error {
  defer n.ctxCancel()
  n.wg.Add(1)
  go n.evStream.StreamEvents()
  state, err := n.stateSync.SyncState()
  if err != nil {
    return err
  }
  n.state = state
  n.wg.Add(1)
  go n.servegRPC()
  n.wg.Add(1)
  go n.peerDisc.DiscoverPeers(n.cfg.Period)
  n.wg.Add(1)
  go n.txRelay.RelayMsgs(n.cfg.Period)
  if n.cfg.Bootstrap {
    path := filepath.Join(n.cfg.KeyStoreDir, string(n.state.Authority()))
    auth, err := chain.ReadAccount(path, []byte(n.cfg.AuthPass))
    if err != nil {
      return err
    }
    n.blockProp.SetAuthority(auth)
    n.blockProp.SetState(n.state)
    n.wg.Add(1)
    go n.blockProp.ProposeBlocks(n.cfg.Period * 2)
  }
  n.wg.Add(1)
  go n.blkRelay.RelayMsgs(n.cfg.Period)
  select {
  case <- n.ctx.Done():
  case err = <- n.chErr:
    fmt.Println(err)
  }
  n.ctxCancel() // restore default signal handling
  n.grpcSrv.GracefulStop()
  n.wg.Wait()
  return err
}
  #+END_SRC

*** The node gRPC server for clients and inter-node communication

- gRPC server :: The gRPC server exposes the account, transaction, block, and
  node services for clients and other nodes to interact with the node. Each gRPC
  service exposes highly cohesive and loosely coupled blockchain functions under
  the well-defined interface described by gRPC messages and methods. Each gRPC
  service depends on specific node components in order to provide the defined
  functions. The gRPC server process is on of the node concurrent processes, so
  all requests combing from the gRPC server and all responses going to the gRPC
  server are concurrent. All gRPC services and methods are concurrency safe as
  they internally rely either on the mutex-based concurrency safe state
  implementation or the channel-based concurrency safe implementation of other
  node concurrent processes. The gRPC server
  - Create a TCP listener on the node address
  - Defer closing the TCP connection after the graceful shutdown of the gRPC
    server
  - Create a new gRPC server
  - Register the node, account, transaction, and block gRPC services with the
    gRPC server
  - Start the gRPC server to accept connections
  #+BEGIN_SRC go
func (n *Node) servegRPC() {
  defer n.wg.Done()
  lis, err := net.Listen("tcp", n.cfg.NodeAddr)
  if err != nil {
    n.chErr <- err
    return
  }
  defer lis.Close()
  fmt.Printf("<=> gRPC %v\n", n.cfg.NodeAddr)
  n.grpcSrv = grpc.NewServer()
  node := rpc.NewNodeSrv(n.peerDisc, n.evStream)
  rpc.RegisterNodeServer(n.grpcSrv, node)
  acc := rpc.NewAccountSrv(n.cfg.KeyStoreDir, n.state)
  rpc.RegisterAccountServer(n.grpcSrv, acc)
  tx := rpc.NewTxSrv(
    n.cfg.KeyStoreDir, n.cfg.BlockStoreDir, n.state.Pending, n.txRelay,
  )
  rpc.RegisterTxServer(n.grpcSrv, tx)
  blk := rpc.NewBlockSrv(n.cfg.BlockStoreDir, n.evStream, n.state, n.blkRelay)
  rpc.RegisterBlockServer(n.grpcSrv, blk)
  err = n.grpcSrv.Serve(lis)
  if err != nil {
    n.chErr <- err
    return
  }
}
  #+END_SRC

- gRPC services and methods :: All communication of clients with the blockchain
  node and all communication between nodes in the peer-to-peer network happens
  exclusively through the gRPC services and methods. Every node provides a CLI
  for clients to interact with the node through the gRPC interface. The CLI can
  interact with both local and remote nodes in exactly the same way. All
  inter-node communication happens through the gRPC interface. Communication
  with clients and inter-node communication uses the gRPC request-response, the
  gRPC client streaming, and the gRPC server streaming
  | gRPC service | gRPC method       | gRPC communication style |
  |--------------+-------------------+--------------------------|
  | =Account=    | =AccountCreate=   | gRPC request-response    |
  | =Account=    | =AccountBalance=  | gRPC request-response    |
  | =Tx=         | =TxSign=          | gRPC request-response    |
  | =Tx=         | =TxSend=          | gRPC request-response    |
  | =Tx=         | =TxReceive=       | gRPC client streaming    |
  | =Tx=         | =TxSearch=        | gRPC server streaming    |
  | =Block=      | =GenesisSync=     | gRPC request-response    |
  | =Block=      | =BlockSync=       | gRPC server streaming    |
  | =Block=      | =BlockReceive=    | gRPC client streaming    |
  | =Block=      | =BlockSearch=     | gRPC server streaming    |
  | =Node=       | =PeerDiscover=    | gRPC request-response    |
  | =Node=       | =StreamSubscribe= | gRPC server streaming    |

*** The node CLI for clients

- Node CLI :: The node CLI allows local and remote clients to start the
  blockchain node, subscribe to the node events, create new accounts on the
  blockchain, query the account balance, sign and send new transactions to the
  blockchain node, search transactions, and search blocks. All communication
  between the client and the node happens through the gRPC interface that is the
  only interface to interact with the node
  | CLI command             | CLI options                                    |
  |-------------------------+------------------------------------------------|
  | ~./bcn account create~  | =--node= target node address                   |
  |                         | =--ownerpass= owner account password           |
  | ~./bcn account balance~ | =--node= target node address                   |
  |                         | =--account= account address                    |
  | ~./bcn tx sign~         | =--node= target node address                   |
  |                         | =--from= sender address                        |
  |                         | =--to= recipient address                       |
  |                         | =--value= transfer amount                      |
  |                         | =--ownerpass= owner account password           |
  | ~./bcn tx send~         | =--node= target node address                   |
  |                         | =--sigtx= signed encoded transaction           |
  | ~./bcn tx search~       | =--node= target node address                   |
  |                         | =--hash= transaction hash prefix               |
  |                         | =--from= sender address prefix                 |
  |                         | =--to= recipient address prefix                |
  |                         | =--account= involved account address prefix    |
  | ~./bcn block search~    | =--node= target node address                   |
  |                         | =--number= block number                        |
  |                         | =--hash= block hash prefix                     |
  |                         | =--parent= parent hash prefix                  |
  | ~./bcn node start~      | =--node= target node address                   |
  |                         | =--bootstrap= bootstrap and authority node     |
  |                         | =--seed= seed node address                     |
  |                         | =--keystore= key store directory               |
  |                         | =--blockstore= block store directory           |
  |                         | =--chain= blockchain name                      |
  |                         | =--authpass= authority account password        |
  |                         | =--ownerpass= owner account password           |
  |                         | =--balance= owner account balance              |
  | ~./bcn node subscribe~  | =--node= target node address                   |
  |                         | =--events= list of event types e.g. blk,tx,all |

** Testing and usage

*** Testing the node start and operation

The =TestNodeStart= testing process
- Set up the bootstrap node
  - Configure the bootstrap node
  - Start the bootstrap node in a separate goroutine
  - Wait for the bootstrap node to start
- Set up a gRPC client connection with the bootstrap node
- Send several transactions to the bootstrap node in a separate goroutine
  - Get the initial owner account and its balance from the genesis
  - Re-create the initial owner account from the genesis
  - Create the gRPC transaction client
  - Start sending transaction to the bootstrap node
    - Create and sign a new transaction
    - Encode the signed transaction
    - Call the gRPC =TxSend= method to the the signed encoded transaction
- Set up the client that subscribes to the node event stream
  - Set up a gRPC client connection with the bootstrap node
  - Create the gRPC node client
  - Call the =StreamSubscribe= method to subscribe to the node event stream and
    establish the gRPC server stream of domain events
  - Define the expected events to receive after a successful block proposal
  - Start consuming events from the gRPC server stream of domain events. For
    each received event
    - Decode the received domain event
    - Verify that the type and the action of the domain event are correct
- Stop gracefully the node
#+BEGIN_SRC fish
go test -v -cover -coverprofile=coverage.cov ./... -run NodeStart
#+END_SRC
