* State sync

** Concepts and purpose

*** Initial state synchronization

- State synchronization :: The initial state sync occurs when either the
  bootstrap node first starts and initializes a new blockchain or when a node
  syncs the confirmed state and the block store with the bootstrap node starting
  from the genesis or from a specific block number. The state sync ensures
  immutability and integrity of the blockchain by verifying signatures of the
  genesis and every block in order, re-applying every block to the confirmed
  state and the block store of every node. The state sync process is performed
  during the bootstrap of a new blockchain. In this case only the genesis is
  created and persisted, and the confirmed state of the bootstrap node is
  initialized with the genesis balances. The state sync process brings a new
  empty node or an out-of-sync node have the verified and validated confirmed
  state as per the latest confirmed block

*** Bootstrap state initialization

- Bootstrap state init :: The bootstrap state init is only performed once on the
  bootstrap node during the initialization of a new blockchain. The bootstrap
  state init creates, signs, and persists the genesis with the initial
  blockchain configuration parameters including the blockchain name, the time of
  signing the genesis, the authority account for signing the genesis and every
  proposed block, the initial owner account with the initial balance. The
  bootstrap state init process also initializes the confirmed state of the
  bootstrap node with balances from the genesis

*** Node state synchronization

- Node state sync :: The node state sync occurs every time when a new node joins
  the blockchain network and needs to verify and validate all confirmed blocks
  on the blockchain starting from the genesis. In this case the genesis is
  fetched from the bootstrap node, the genesis signature is verified, and the
  genesis is persisted to the block store. All the confirmed blocks are fetched
  either from the bootstrap node or any other know peer that has newer confirmed
  blocks that the bootstrap node. The node state sync is also performed when an
  out-of-sync node is catching up with the latest confirmed blocks on the
  blockchain. In this case the genesis and the initial confirmed blocks are
  already verified, validated, and persisted. The initial confirmed blocks are
  read and applied to the confirmed state from the local block store. Only the
  newer confirmed blocks are fetched from the bootstrap node and known peers.
  Regardless of a new node or an out-of-sync node, every fetched node including
  the genesis goes through the verification of the signature and the full
  validation in the form of the block application. Every verified, validated,
  and confirmed block is applied to the node's confirmed state and appended to
  the block store. Once the node state sync process is finished the node is
  ready to receive and relay new transactions, to receive and relay new proposed
  blocks, and to verify and validated new proposed blocks. The node state sync
  process is only executed when the node starts.

** Design and implementation

*** The state synchronization algorithm

- State sync algorithm :: The state synchronization algorithm covers both the
  bootstrap node initialization and the node synchronization. The algorithms
  starts by reading the genesis from a local file system. If the genesis is not
  present, the genesis is created for the bootstrap node or is fetched from the
  bootstrap node for a peer node. In either case the genesis signature is
  verified and the new blockchain state is initialized with the genesis. Next
  the local block store is initialized if necessary. Then the confirmed blocks
  from the local block store are read and applied to the confirmed state.
  Finally the new confirmed blocks are fetched from all known peers, verified,
  validated, and applied to the confirmed state. The state synchronization
  algorithm
  - Read the genesis from the local block store. If the genesis is not present
    - For the bootstrap node create, sign, and persist the genesis
    - For a peer node fetch the genesis from the bootstrap node, verify,
      validate, and persist the genesis
  - initialize the confirmed state with the genesis
  - Initialize the local block store if necessary
  - Read, verify, validate, and apply to the confirmed state the confirmed
    blocks from the local block store
  - Fetch, verify, validate, and apply to the confirmed sate the confirmed
    blocks from all know peers
  #+BEGIN_SRC go
func (s *stateSync) syncState() (*chain.State, error) {
  gen, err := chain.ReadGenesis(s.cfg.BlockStoreDir)
  if err != nil {
    if s.cfg.Bootstrap {
      gen, err = s.createGenesis()
      if err != nil {
        return nil, err
      }
    } else {
      gen, err = s.syncGenesis()
      if err != nil {
        return nil, err
      }
    }
  }
  valid, err := chain.VerifyGen(gen)
  if err != nil {
    return nil, err
  }
  if !valid {
    return nil, fmt.Errorf("invalid genesis signature")
  }
  s.state = chain.NewState(gen)
  err = chain.InitBlockStore(s.cfg.BlockStoreDir)
  if err != nil {
    return nil, err
  }
  err = s.readBlocks()
  if err != nil {
    return nil, err
  }
  err = s.syncBlocks()
  if err != nil {
    return nil, err
  }
  fmt.Printf("== Sync state\n%v", s.state)
  return s.state, nil
}
  #+END_SRC

** Testing and usage
